(define (square x)
    (* x x))
(define (sum-of-squares x y)
    (+ (square x) (square y)))
(sum-of-squares 3 4)
(define (abs1 x)
    (cond ((> x 0) x)
        ((= x 0) 0)
        ((< x 0) (- x))))
(define (abs x)
    (if (< x 0)
        (- x)
        x))
(abs 10)
(abs 0)
(abs (- 10))
;;EXERCISE 1.1
(define a 3)
