; (define (factorial n)
;     (if (= n 1)
;         1
;         (* n (factorial(- n 1)))))
; (factorial 6)

(define (factorial n)
    (define (factorial-iter product counter)
        (if (> counter n)
        product
            (factorial-iter (* product counter)
                (+ counter 1))))
    (factorial-iter 1 1))
(factorial 6)
; (define (inc a)
;     (+ a 1))
; (define (dec a)
;     (- a 1))
; (define (+ a b)
;     (if (= a 0)
;         b)
;         (inc (+ (dec a) b)))
; (define (+ a b)
;     (if (= a 0)
;         b)
;         (+ (dec a) (inc b)))

(define (A x y)
  (cond ((= y 0) 0)
        ((= x 0) (* 2 y))
        ((= y 1) 2)
        (else (A (- x 1)
                 (A x (- y 1))))))
(A 1 10)
(A 2 4)
(A 3 3)
; (define (fib n)
;     (cond ((= n 0) 0)
;           ((= n 1) 1)
;           (else (+ (fib (- n 1))
;                   (fib (- n 2))))))

(define (fib n)
    (fib-iter 1 0 n))
(define (fib-iter a b count)
    (if (= count 0)
        b
        (fib-iter (+ a b) a (- count 1))))

(fib 0)
(fib 1)
(fib 2)
(fib 5)
(fib 6)

(define (count-change amount)
    (cc amount 5))
(define (cc amount kinds-of-coins)
    (cond ((= amount 0) 1)
          ((or (< amount 0) (= kinds-of-coins 0)) 0)
          (else (+ (cc amount (- kinds-of-coins 1))
                   (cc (- amount 
                        (first-denomination kinds-of-coins)) 
                    kinds-of-coins)))))

(define (first-denomination kinds-of-coins)
    (cond ((= kinds-of-coins 1) 1)
          ((= kinds-of-coins 2) 5)
          ((= kinds-of-coins 3) 10)
          ((= kinds-of-coins 4) 25)
          ((= kinds-of-coins 5) 50)))
(count-change 100)
(define (f1 n)
    (if (< n 3) n
        (+ (f1 (- n 1)) (f1 (- n 2)) (f1 (- n 3)) )
    ))

(define (f n)
    (define (f-item a b c count)
       (cond ((= count 0) c)
             ((= count 1) b) 
             ((= count 2) a)
             (else (f-item (+ a b c) a b (- count 1)))
        )
    )
    (f-item 2 1 0 n)
)
(define (check n)
    (if (= (f1 n) (f n)) 1
    0))
(check 0)
(check 1)
(check 2)
(check 6)
(check 7)